routes/web.php
<?php


use App\Leave;
use App\Leave_user;
use App\User;
use App\Role;
use App\Oficina;
use App\Departamento;
use App\Puesto;
use App\Historial;
use App\Profile;
use App\Nivel;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('test', function () {
  $a = Puesto::with('pNivel')->get();


  //$puesto = Puesto::with('pnivel')->get();
  /*$nivel =  Nivel::with('puestos')->where('id', '=', 1)->get();
    $dropdown = '';
    foreach($nivel as $puestos){
       $dropdown = $puestos->puestos;
    }
    return response()->json($dropdown); */
    //  return view('welcome');
});


//Route::get('/sendmail', 'SolicitudesController@sendMail')->name('sendmail');

Route::get('examples', function (){
    $leaves = Leave::with('users')->get();

});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/pdf', 'SolicitudesController@pdf')->name('pdf');



Route::get('/dashboard','DashboardController@index')->name('dashboard');

Route::get('/logout','Auth\LoginController@logout')->name('logout');


/**
 *  States Route(s)
 */
Route::resource('/employees','EmployeesController');
Route::post('employees/search','EmployeesController@search')->name('employees.search');


Route::get('ajaxVacaciones', 'EmployeesController@ajaxVacaciones');
Route::post('ajaxVacaciones', 'EmployeesController@ajaxVacacionesPost');




Route::get('getNiveles/{any}', 'EmployeesController@getNiveles');
Route::post('getNiveles/{any}', 'EmployeesController@getNivelesPost');




/**
 *  Catalogos Oficinas - Departamentos - Puestos y Salarios
 */

Route::resource('/oficinas','OficinasController');
Route::post('oficinas/search','OficinasController@search')->name('oficinas.search');

Route::resource('/departamentos','DepartamentosController');
Route::post('departamentos/search','DepartamentosController@search')->name('departamentos.search');

Route::resource('/puestos','PuestosController');
Route::post('puestos/search','PuestosController@search')->name('puestos.search');

Route::resource('/leaves','LeavesController');
Route::post('leaves/search','LeavesController@search')->name('leaves.search');

Route::resource('/solicitudes','SolicitudesController');
Route::post('solicitudes/search','SolicitudesController@search')->name('solicitudes.search');

Route::post('solicitudes/{solicitude}/preaprobar','SolicitudesController@preaprobar')->name('solicitudes.preaprobar');
Route::get('solicitudes/{solicitude}/preaprobar','SolicitudesController@preaprobar')->name('solicitudes.preaprobar');

Route::post('solicitudes/{solicitude}/aceptar','SolicitudesController@aceptar')->name('solicitudes.aceptar');
Route::get('solicitudes/{solicitude}/aceptar','SolicitudesController@aceptar')->name('solicitudes.aceptar');

Route::post('solicitudes/{solicitude}/rechazar','SolicitudesController@rechazar')->name('solicitudes.rechazar');
Route::get('solicitudes/{solicitude}/rechazar','SolicitudesController@rechazar')->name('solicitudes.rechazar');


/* obtiene json asignadas, usadas, disponibles*/
Route::post('solicitudes/getSalidas/{any}','SolicitudesController@getSalidas')->name('solicitudes.getSalidas');
Route::get('solicitudes/getSalidas/{any}','SolicitudesController@getSalidas')->name('solicitudes.getSalidas');


/*Vista para conocer tus propias Vacaciones*/
Route::post('getSalidas','HomeController@index')->name('Home.getSalidas');
Route::get('getSalidas','HomeController@index')->name('Home.getSalidas');

resources/views/home.blade.php
@extends('layouts.app')

                <?php use App\User ;

                    $user = User::with('roles')->find(Auth::user()->id);
                    $rol =  $user->roles;

                    foreach($rol as $r){
                     $rolling = $r->name;
                    }

                ?>


@section('content')


    <br>
    <div>


        <div class="row white-text">

            <a href="#" class="white-text">
                <div class="mx-20 card-panel blue lighten-1 col s18 offset-s2 m4 offset-m2 l4 offset-l2 xl2 offset-xl1 ml-14">
                    <div class="row">
                        <div class="col s7 m7 xl7">
                            <i class="material-icons medium white-text pt-5">perm_contact_calendar
                                </i>
                            <h6 class="no-padding txt-md">Vacaciones por Contrato</h6>
                        </div>
                        <div class="col s5 m5 xl5 ">
                        <h3 class="no-padding center mt">{{$total}} </h3>
                        </div>
                    </div>
                </div>
            </a>
            <a href="#" class="white-text">
                <div class="mx-20 card-panel teal lighten-1 col s8 offset-s2 m4 l4 xl2">
                    <div class="row">
                        <div class="col s7 xl7">
                            <i class="material-icons medium white-text pt-5">check</i>
                            <h6 class="no-padding txt-md">Vacaciones Aprobadas</h6>
                        </div>
                        <div class="col s5 xl5">
                            <h3 class="no-padding center mt "> {{$usadas}}</h3>
                        </div>
                    </div>
                </div>
            </a>
            <a href="#" class="white-text">
                <div class="mx-20 card-panel orange lighten-1 col s8 offset-s2 m4 offset-m2 l4 offset-l2 xl2">
                    <div class="row">
                        <div class="col s7 xl7">
                            <i class="material-icons medium white-text pt-5">card_travel</i>
                            <h6 class="no-padding txt-md">Tienes Disponibles</h6>
                        </div>
                        <div class="col s5 xl5">
                        <h3 class="no-padding center mt ">{{$final}} </h3>
                        </div>
                    </div>
                </div>
            </a>
            <a href="#" class="white-text hide-on-small-only">
                <div class="mx-20 card-panel red lighten-1 col s8 offset-s2 m4 l4 xl2">
                    <div class="row">
                        <div class="col s7 xl7">
                            <i class="material-icons medium white-text pt-5">cancel</i>
                            <h6 class="no-padding txt-md">Vacaciones Rechazadas</h6>
                        </div>
                        <div class="col s5 xl5">
                        <h3 class="no-padding center mt "> {{$canceladas}}</h3>
                            </div>
                    </div>
                </div>
            </a>


        </div>
    </div>
   <!--  <div class="container-fluid">
        <div class="card-panel">
           <canvas id="employee"></canvas>
        </div>
    </div>  -->
    <br>


<div class="container">


        <div class="row">
                <div class="col s12 m6">
                  <div class="card">
                    <div class="card-image">
                      <img src="{{asset('img/plane.jfif')}}">
                      <span class="card-title">Mis Vacaciones</span>
                      <a href="{{route('solicitudes.create')}}" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">forward</i></a>
                    </div>
                    <div class="card-content">
                      <p>Solicita tus Vacaciones, desde nuestro portal, si es Aprobada o Rechazada, te lo haremos saber automáticamente a tu correo electrónico.</p>
                    </div>
                  </div>
                </div>
                <div class="col s12 m6">
                        <div class="card">
                          <div class="card-image">
                            <img width="50%" src="{{asset('img/profil.jpg')}}">
                            <span class="card-title">Mi Perfil</span>
                            <a href="{{route('solicitudes.create')}}" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">visibility</i></a>
                          </div>
                          <div class="card-content">
                            <p>Revisa, tus datos personales y laborales a lo largo de tu tiempo en BLM.</p>
                          </div>
                        </div>
                      </div>
              </div>

       <!-- <div class="fixed-action-btn">
                <a class="btn-floating btn-large waves=effect waves-light red" href="{{route('employees.create')}}">
                    <i class="large material-icons">add</i>
                </a>
            </div>-->

           <!-- <div class="row">
                    <div class="card col s12 m12 l12 xl12 mt-5">
                        <div>
                        <h4 class="center grey-text text-darken-2 card-title">Mi Perfil</h4>
                        </div>
                        <hr>
                        <div class="card-content">

                        </div>
                    </div>
                </div> -->

</div>





@endsection