routes/web.php
<?php


use App\Leave;
use App\Leave_user;
use App\User;
use App\Role;
use App\Oficina;
use App\Departamento;
use App\Puesto;
use App\Historial;
use App\Profile;
use App\Nivel;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('test', function () {
  $a = Puesto::with('pNivel')->get();


  //$puesto = Puesto::with('pnivel')->get();
  /*$nivel =  Nivel::with('puestos')->where('id', '=', 1)->get();
    $dropdown = '';
    foreach($nivel as $puestos){
       $dropdown = $puestos->puestos;
    }
    return response()->json($dropdown); */
    //  return view('welcome');
});


//Route::get('/sendmail', 'SolicitudesController@sendMail')->name('sendmail');

Route::get('examples', function (){
    $leaves = Leave::with('users')->get();

});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/pdf', 'SolicitudesController@pdf')->name('pdf');



Route::get('/dashboard','DashboardController@index')->name('dashboard');

Route::get('/logout','Auth\LoginController@logout')->name('logout');


/**
 *  States Route(s)
 */
Route::resource('/employees','EmployeesController');
Route::post('employees/search','EmployeesController@search')->name('employees.search');


Route::get('ajaxVacaciones', 'EmployeesController@ajaxVacaciones');
Route::post('ajaxVacaciones', 'EmployeesController@ajaxVacacionesPost');




Route::get('getNiveles/{any}', 'EmployeesController@getNiveles');
Route::post('getNiveles/{any}', 'EmployeesController@getNivelesPost');




/**
 *  Catalogos Oficinas - Departamentos - Puestos y Salarios
 */

Route::resource('/oficinas','OficinasController');
Route::post('oficinas/search','OficinasController@search')->name('oficinas.search');

Route::resource('/departamentos','DepartamentosController');
Route::post('departamentos/search','DepartamentosController@search')->name('departamentos.search');

Route::resource('/puestos','PuestosController');
Route::post('puestos/search','PuestosController@search')->name('puestos.search');

Route::resource('/leaves','LeavesController');
Route::post('leaves/search','LeavesController@search')->name('leaves.search');

Route::resource('/solicitudes','SolicitudesController');
Route::post('solicitudes/search','SolicitudesController@search')->name('solicitudes.search');

Route::post('solicitudes/{solicitude}/preaprobar','SolicitudesController@preaprobar')->name('solicitudes.preaprobar');
Route::get('solicitudes/{solicitude}/preaprobar','SolicitudesController@preaprobar')->name('solicitudes.preaprobar');

Route::post('solicitudes/{solicitude}/aceptar','SolicitudesController@aceptar')->name('solicitudes.aceptar');
Route::get('solicitudes/{solicitude}/aceptar','SolicitudesController@aceptar')->name('solicitudes.aceptar');

Route::post('solicitudes/{solicitude}/rechazar','SolicitudesController@rechazar')->name('solicitudes.rechazar');
Route::get('solicitudes/{solicitude}/rechazar','SolicitudesController@rechazar')->name('solicitudes.rechazar');


/* obtiene json asignadas, usadas, disponibles*/
Route::post('solicitudes/getSalidas/{any}','SolicitudesController@getSalidas')->name('solicitudes.getSalidas');
Route::get('solicitudes/getSalidas/{any}','SolicitudesController@getSalidas')->name('solicitudes.getSalidas');


/*Vista para conocer tus propias Vacaciones*/
Route::post('getSalidas','HomeController@index')->name('Home.getSalidas');
Route::get('getSalidas','HomeController@index')->name('Home.getSalidas');

app/Puesto.php
<?php

namespace App;
use App\Historial;
use App\Profile;
use App\Nivel;

use Illuminate\Database\Eloquent\Model;

class Puesto extends Model
{
    protected $table = 'puestos';

    public function pHistorial(){
        return $this->belongsTo('App\Historial');
    }

    public function pProfile(){
        return $this->belongsTo('App\Profile');
    }

    public function  pNivel(){
        return $this->belongsTo('App\Nivel', 'nivel_id', 'id');
    }




}

app/Http/Controllers/PuestosController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\User;
use App\Oficina;
use App\Departamento;
use App\Puesto;
use App\Leaves;
use App\Historial;
use App\Nivel;

use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;



class PuestosController extends Controller
{

    public function __construct(){
        $this->middleware('auth');
    }

      /**
     *  Search For Resource(s)
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
        public function search(Request $request){
            $this->validate($request,[
                'search'   => 'required|min:1',
                'options'  => 'required'
            ]);
            $str = $request->input('search');
            $option = $request->input('options');
            $puestos = Puesto::where($option, 'LIKE' , '%'.$str.'%')->Paginate(4);
            return view('puestos.index')->with(['puestos' => $puestos , 'search' => true ]);
        }


  /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
        public function index(Request $request)
        {
            $request->user()->authorizeRoles(['admin']);

            $puestos = Puesto::get();
            return view('puestos.index')->with('puestos',$puestos);
        }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
         public function create()
        {
            $nivel = Nivel::get();
            return view('puestos.create')->with([

                'niveles' => $nivel

                ]);        }




    public function edit($id){

        $puesto = Puesto::find($id);

        $nivel = Nivel::get();

        return view('puestos.edit')->with([

            'oficina' => $puesto,
            'niveles' => $nivel

            ]);

     }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->user()->authorizeRoles(['admin']);

        $this->validate($request,[
            'nombre' => 'required|min:4|unique:puestos',
            'nivel' => 'required',
        ]);

        $puesto = new Puesto();
        $puesto->nombre = $request->input('nombre');
        $puesto->salario = 0;
        $puesto->nivel_id = $request->input('nivel');

        $puesto->save();

         return redirect('/puestos')->with('info','Puesto Creado!');
    }




             /**
     * Edit a existing resource
     *
     *  @param \Illuminate\Http\Request
     *  @param  int  $id
     *  @return \Illuminate\Http\Response
     */

    public function update(Request $request, $id){



        $request->user()->authorizeRoles(['admin']);

        $this->validateRequest($request,$id);

        $puesto = Puesto::find($id);

        $puesto->nombre = $request->input('nombre');
        $puesto->salario = 0;
        $puesto->nivel_id = $request->input('nivel');

        $puesto ->save();

        return redirect('/puestos')->with('info','Se ha actualizado el departamento con exito!');

     }





/**
     * This method is used for validating the form
     *
     * @param  \Illuminate\Http\Request  $request
     * @return $this
     */
    private function validateRequest($request,$id){

        return $this->validate($request,[
            'nombre'     =>  'required|min:3|max:50',
            'nivel'      =>  'required'
            ]);

        }







}

resources/views/puestos/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card col s12 m8 offset-m2 l8 offset-l2 xl8 offset-xl2 card-mt-15">
                <h4 class="center grey-text text-darken-2 card-title">Agregar Puesto</h4>
                <div class="card-content">
                    <div class="row">
                        <form action="{{route('puestos.store')}}" method="POST">

                                <div class="input-field">
                                    <i class="material-icons prefix">account_balance</i>
                                        <input type="text" name="nombre" id="nombre" class="validate" value="{{ Request::old('nombre') ? : '' }}">
                                        <label for="nombre">Nombre de Puesto</label>
                                        <span class="{{$errors->has('nombre') ? 'helper-text red-text' : '' }}">{{$errors->first('nombre')}}</span>
                                </div>


                                <div class="input-field">
                                    <i class="material-icons prefix">account_balance</i>
                                      <select name="nivel">

                                        @foreach($niveles as $level)

                                             <option value="{{$level->id}}">{{$level->nombre}}</option>

                                        @endforeach

                                      </select>
                                    <label for="nivel">Nivel</label>
                                    </div>

                            @csrf()
                            <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Agregar</button>
                        </form>
                    </div>
                </div>
                <div class="card-action">
                    <a href="/puestos">Regresar</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/puestos/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card col s12 m8 offset-m2 l8 offset-l2 xl8 offset-xl2 card-mt-15">



                <h4 class="center grey-text text-darken-2 card-title">Editar Puesto</h4>
                <div class="card-content">
                    <div class="row">
                            <form action="{{route('puestos.update', $oficina->id)}}" method="POST" >
                            <div class="input-field">
                            <i class="material-icons prefix">account_balance</i>
                                <input type="text" name="nombre" id="nombre" class="validate" value="{{ Request::old('nombre') ? : $oficina->nombre}} ">
                                <label for="nombre">Nombre de Puesto</label>
                                <span class="{{$errors->has('nombre') ? 'helper-text red-text' : '' }}">{{$errors->first('nombre')}}</span>
                            </div>
                            <div class="input-field">
                                <i class="material-icons prefix">account_balance</i>
                                  <select name="nivel">

                                    @foreach($niveles as $level)

                                  <option value="{{$level->id}}"   {{  ( $oficina->nivel_id === $level->id ) ? 'selected="selected"'  : '' }} >{{$level->nombre}} </option>

                                    @endforeach

                                  </select>
                                </div>

                                @method('PUT')
                                @csrf()
                            <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Actualizar</button>
                        </form>
                    </div>
                </div>
                <div class="card-action">
                    <a href="/oficinas">Regresar</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/puestos/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h4 class="grey-text text-darken-1 center">Puestos</h4>
    {{-- Search --}}
    <div class="row mb-0">
        <ul class="collapsible">
            <li>
                <div class="collapsible-header">
                    <i class="material-icons">Buscar</i>
                    Buscar Puestos
                </div>
                <div class="collapsible-body">
                    <div class="row mb-0">
                        <form action="{{route('puestos.search')}}" method="POST">
                            @csrf()
                            <div class="input-field col s12 m6 l5 xl6">
                                <input id="search" type="text" name="search" >
                                <label for="search">Buscar puestos</label>
                                <span class="{{$errors->has('search') ? 'helper-text red-text' : '' }}">{{$errors->has('search') ? $errors->first('search') : '' }}</span>
                            </div>
                            <div class="input-field col s12 m6 l4 xl4">
                                <select name="options" id="options">
                                    <option value="nombre">Nombre(s)</option>
                                </select>
                                <label for="options">Buscar por Opciones</label>
                            </div>
                            <br>
                            <div class="col l2">
                                <button type="submit" class="btn waves-effect waves-light">Buscar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    {{-- Search END --}}
        <!-- Show All Employee List as a Card -->
    <div class="card">
        <div class="card-content">
            <div class="row">
                <h5 class="pl-15 grey-text text-darken-2">Lista de Puestos</h5>
                <!-- Table that shows Employee List -->
                <table class="responsive-table col s12 m12 l12 xl12">
                    <thead class="grey-text text-darken-1">
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody id="emp-table">
                        <!-- Check if there are any employee to render in view -->
                        @if($puestos->count())
                            @foreach($puestos as $puesto)
                                <tr>
                                    <td>{{$puesto->id}}</td>
                                    <td>{{$puesto->nombre}}</td>
                                    <td>
                                    <a href="{{route('puestos.edit',$puesto->id)}}" class="btn btn-small btn-floating waves=effect waves-light teal lighten-2"><i class="material-icons">list</i></a>
                                    </td>
                                </tr>
                            @endforeach
                            @if(isset($search))
                                <tr>
                                    <td colspan="4">
                                        <a href="/puestos" class="right">Ver Todos</a>
                                    </td>
                                </tr>
                            @endif
                        @else
                            {{-- if there are no puestos then show this message --}}
                            <tr>
                                <td colspan="5"><h6 class="grey-text text-darken-2 center">No se encontraron registros!</h6></td>
                            </tr>
                        @endif
                    </tbody>
                </table>
                <!-- puestos Table END -->
            </div>
            <!-- Show Pagination Links -->
        <!--    <div class="center">
            $puestos->links('vendor.pagination.default',['paginator' => $puestos])}}
            </div> -->
        </div>
    </div>
    <!-- Card END -->
</div>
<!-- This is the button that is located at the right bottom, that navigates us to puestos.create view -->
<div class="fixed-action-btn">
    <a class="btn-floating btn-large waves=effect waves-light red" href="{{route('puestos.create')}}">
        <i class="large material-icons">add</i>
    </a>
</div>
@endsection