routes/web.php
<?php


use App\Leave;
use App\Leave_user;
use App\User;
use App\Role;
use App\Oficina;
use App\Departamento;
use App\Puesto;
use App\Historial;
use App\Profile;
use App\Nivel;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('test', function () {
  $a = Puesto::with('pNivel')->get();


  //$puesto = Puesto::with('pnivel')->get();
  /*$nivel =  Nivel::with('puestos')->where('id', '=', 1)->get();
    $dropdown = '';
    foreach($nivel as $puestos){
       $dropdown = $puestos->puestos;
    }
    return response()->json($dropdown); */
    //  return view('welcome');
});


//Route::get('/sendmail', 'SolicitudesController@sendMail')->name('sendmail');

Route::get('examples', function (){
    $leaves = Leave::with('users')->get();

});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/pdf', 'SolicitudesController@pdf')->name('pdf');



Route::get('/dashboard','DashboardController@index')->name('dashboard');

Route::get('/logout','Auth\LoginController@logout')->name('logout');


/**
 *  States Route(s)
 */
Route::resource('/employees','EmployeesController');
Route::post('employees/search','EmployeesController@search')->name('employees.search');


Route::get('ajaxVacaciones', 'EmployeesController@ajaxVacaciones');
Route::post('ajaxVacaciones', 'EmployeesController@ajaxVacacionesPost');




Route::get('getNiveles/{any}', 'EmployeesController@getNiveles');
Route::post('getNiveles/{any}', 'EmployeesController@getNivelesPost');




/**
 *  Catalogos Oficinas - Departamentos - Puestos y Salarios
 */

Route::resource('/oficinas','OficinasController');
Route::post('oficinas/search','OficinasController@search')->name('oficinas.search');

Route::resource('/departamentos','DepartamentosController');
Route::post('departamentos/search','DepartamentosController@search')->name('departamentos.search');

Route::resource('/puestos','PuestosController');
Route::post('puestos/search','PuestosController@search')->name('puestos.search');

Route::resource('/leaves','LeavesController');
Route::post('leaves/search','LeavesController@search')->name('leaves.search');

Route::resource('/solicitudes','SolicitudesController');
Route::post('solicitudes/search','SolicitudesController@search')->name('solicitudes.search');

Route::post('solicitudes/{solicitude}/preaprobar','SolicitudesController@preaprobar')->name('solicitudes.preaprobar');
Route::get('solicitudes/{solicitude}/preaprobar','SolicitudesController@preaprobar')->name('solicitudes.preaprobar');

Route::post('solicitudes/{solicitude}/aceptar','SolicitudesController@aceptar')->name('solicitudes.aceptar');
Route::get('solicitudes/{solicitude}/aceptar','SolicitudesController@aceptar')->name('solicitudes.aceptar');

Route::post('solicitudes/{solicitude}/rechazar','SolicitudesController@rechazar')->name('solicitudes.rechazar');
Route::get('solicitudes/{solicitude}/rechazar','SolicitudesController@rechazar')->name('solicitudes.rechazar');


/* obtiene json asignadas, usadas, disponibles*/
Route::post('solicitudes/getSalidas/{any}','SolicitudesController@getSalidas')->name('solicitudes.getSalidas');
Route::get('solicitudes/getSalidas/{any}','SolicitudesController@getSalidas')->name('solicitudes.getSalidas');


/*Vista para conocer tus propias Vacaciones*/
Route::post('getSalidas','HomeController@index')->name('Home.getSalidas');
Route::get('getSalidas','HomeController@index')->name('Home.getSalidas');

app/Departamento.php
<?php

namespace App;
use App\Historial;
use App\Profile;
use Illuminate\Database\Eloquent\Model;

class Departamento extends Model
{

    protected $table = 'departamentos';

    public function dHistorial(){
        return $this->belongsTo('App\Historial');
    }


    public function dProfile(){
        return $this->belongsTo('App\Profile');
    }


}

app/Http/Controllers/DepartamentosController.php
<?php

namespace App\Http\Controllers;


use App\Role;
use App\User;
use App\Oficina;
use App\Departamento;
use App\Puesto;
use App\Leaves;
use App\Historial;

use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;



class DepartamentosController extends Controller
{

    public function __construct(){
        $this->middleware('auth');
    }



      /**
     *  Search For Resource(s)
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
        public function search(Request $request){
            $this->validate($request,[
                'search'   => 'required|min:1',
                'options'  => 'required'
            ]);
            $str = $request->input('search');
            $option = $request->input('options');
            $departamentos = Departamento::where($option, 'LIKE' , '%'.$str.'%')->Paginate(4);
            return view('departamentos.index')->with(['departamentos' => $departamentos , 'search' => true ]);
        }


  /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
        public function index(Request $request)
        {
            $request->user()->authorizeRoles(['admin']);

            $departamentos = Departamento::get();
            return view('departamentos.index')->with('departamentos',$departamentos);
        }



     /**
     * Edita a listing of the resource.
     * @param int
     * @return \Illuminate\Http\Response
     */

        public function edit(Request $resquest, $id){
                $departamento = Departamento::find($id);
                return view('departamentos.edit')->with('departamento' ,$departamento);
        }


             /**
     * Edit a existing resource
     *
     *  @param \Illuminate\Http\Request
     *  @param  int  $id
     *  @return \Illuminate\Http\Response
     */

     public function update(Request $request, $id){
        $request->user()->authorizeRoles(['admin']);

        $this->validateRequest($request,$id);

        $departamento = Departamento::find($id);

        $departamento->nombre = $request->input('nombre');
        $departamento ->save();

        return redirect('/departamentos')->with('info','Se ha actualizado el departamento con exito!');

     }



/**
     * This method is used for validating the form
     *
     * @param  \Illuminate\Http\Request  $request
     * @return $this
     */
    private function validateRequest($request,$id){

        return $this->validate($request,[
            'nombre'     =>  'required|min:3|max:50',
            ]);

        }






    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
         public function create()
        {

            return view('departamentos.create');
        }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->user()->authorizeRoles(['admin']);

        $this->validate($request,[
            'nombre' => 'required|min:4|unique:departamentos',
        ]);

        $departamento = new Departamento();
        $departamento->nombre = $request->input('nombre');
        $departamento->save();

         return redirect('/departamentos')->with('info','Departamento Creado!');
    }


}

resources/views/departamentos/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card col s12 m8 offset-m2 l8 offset-l2 xl8 offset-xl2 card-mt-15">
                <h4 class="center grey-text text-darken-2 card-title">Agregar Departamento</h4>
                <div class="card-content">
                    <div class="row">
                        <!--
                            $errors has all validation errors if you wanna
                            show validation failure message then you can use it
                            like below.
                            $errors->has('input name') will return boolean
                            Request::old('input name') will return the value of the input field
                            that we have submitted.
                            $errors->first('input name') will return the first validation error,
                            so you can show it on the form.
                        -->
                        <form action="{{route('departamentos.store')}}" method="POST">
                            <div class="input-field">
                            <i class="material-icons prefix">account_balance</i>                               
                                <input type="text" name="nombre" id="nombre" class="validate" value="{{ Request::old('nombre') ? : '' }}">
                                <label for="nombre">Nombre de Departamento / Area</label>                               
                                <span class="{{$errors->has('nombre') ? 'helper-text red-text' : '' }}">{{$errors->first('nombre')}}</span>
                            </div>                          
                            @csrf()
                            <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Add</button>
                        </form>
                    </div>
                </div>
                <div class="card-action">
                    <a href="/departamentos">Go Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/departamentos/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card col s12 m8 offset-m2 l8 offset-l2 xl8 offset-xl2 card-mt-15">
                <h4 class="center grey-text text-darken-2 card-title">Editar Departamento/Area</h4>
                <div class="card-content">
                    <div class="row">
                            <form action="{{route('departamentos.update', $departamento->id)}}" method="POST" >
                            <div class="input-field">
                            <i class="material-icons prefix">account_balance</i>
                                <input type="text" name="nombre" id="nombre" class="validate" value="{{ Request::old('nombre') ? : $departamento->nombre}} ">
                                <label for="nombre">Nombre de Oficina</label>
                                <span class="{{$errors->has('nombre') ? 'helper-text red-text' : '' }}">{{$errors->first('nombre')}}</span>
                            </div>


                                @method('PUT')
                                @csrf()
                            <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Actualizar</button>
                        </form>
                    </div>
                </div>
                <div class="card-action">
                    <a href="/departamentos">Regresar</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/departamentos/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    <div class="card">
        <div class="card-content">
            <div class="row">
                <h5 class="pl-15 grey-text text-darken-2">Lista de Departamentos/Areas</h5>
                <!-- Table that shows Employee List -->
                <table class="responsive-table col s12 m12 l12 xl12">
                    <thead class="grey-text text-darken-1">
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody id="emp-table">
                        <!-- Check if there are any employee to render in view -->
                        @if($departamentos->count())
                            @foreach($departamentos as $departamento)
                                <tr>
                                    <td>{{$departamento->id}}</td>
                                    <td>{{$departamento->nombre}}</td>
                                    <td>
                                    <a href="{{route('departamentos.edit',$departamento->id)}}" class="btn btn-small btn-floating waves=effect waves-light teal lighten-2"><i class="material-icons">list</i></a>
                                    </td>
                                </tr>
                            @endforeach
                            @if(isset($search))
                                <tr>
                                    <td colspan="4">
                                        <a href="/departamentos" class="right">Ver Todos</a>
                                    </td>
                                </tr>
                            @endif
                        @else
                            {{-- if there are no departamentos then show this message --}}
                            <tr>
                                <td colspan="5"><h6 class="grey-text text-darken-2 center">No se encontraron registros!</h6></td>
                            </tr>
                        @endif
                    </tbody>
                </table>
                <!-- departamentos Table END -->
            </div>
            <!-- Show Pagination Links -->
        <!--    <div class="center">
            $departamentos->links('vendor.pagination.default',['paginator' => $departamentos])}}
            </div> -->
        </div>
    </div>
    <!-- Card END -->
</div>
<!-- This is the button that is located at the right bottom, that navigates us to departamentos.create view -->
<div class="fixed-action-btn">
    <a class="btn-floating btn-large waves=effect waves-light red" href="{{route('departamentos.create')}}">
        <i class="large material-icons">add</i>
    </a>
</div>
@endsection